export const neighbourhoods = [
  "Albany Park (Albany Park, Mayfair, North Mayfair, Ravenswood Manor)",
  "Archer Heights (Archer Heights)",
  "Armour Square (Armour Square, Chinatown, Wentworth Gardens)",
  "Ashburn (Ashburn, Ashburn Estates, Beverly View, Crestline, Parkview, Scottsdale, Wrightwood)",
  "Auburn Gresham (Auburn Gresham, Gresham)",
  "Austin (Austin, Galewood, The Island)",
  "Avalon Park (Avalon Park, Marynook, Stony Island Park)",
  "Avondale (Avondale, Jackowo, WacÅ?awowo)",
  "Belmont Cragin (Brickyard, Cragin, Hanson Park)",
  "Beverly (Beverly, West Beverly)",
  "Bridgeport (Bridgeport)",
  "Brighton Park (Brighton Park)",
  "Burnside (Burnside)",
  "Calumet Heights (Calumet Heights, Pill Hill)",
  "Chatham (Chatham, West Chesterfield)",
  "Chicago Lawn (Chicago Lawn, Lithuanian Plaza, Marquette Park)",
  "Clearing (Chrysler Village, Clearing)",
  "Douglas (Bronzeville, Douglas, Groveland Park, Lake Meadows, Prairie Shores, South Commons)",
  "Dunning (Belmont Heights, Belmont Terrace, Dunning, Irving Woods, Schorsch Village)",
  "East Garfield Park (East Garfield Park, Fifth City)",
  "East Side (East Side)",
  "Edgewater (Andersonville, Edgewater, Edgewater Glen, Epic, Lakewood/Balmoral)",
  "Edison Park (Edison Park)",
  "Englewood (Englewood, Hamilton Park)",
  "Forest Glen (Edgebrook, Forest Glen, Middle Edgebrook, Sauganash, Wildwood)",
  "Fuller Park (Fuller Park)",
  "Garfield Ridge (Garfield Ridge, Le Claire Courts, Sleepy Hollow, Vittum Park)",
  "Grand Boulevard (Grand Boulevard)",
  "Greater Grand Crossing (Grand Crossing, Greater Grand Crossing, Park Manor)",
  "Hegewisch (Hegewisch)",
  "Hermosa (Belmont Gardens, Hermosa, Kelvyn Park)",
  "Humboldt Park (Humboldt Park)",
  "Hyde Park (Hyde Park)",
  "Irving Park (Irving Park, Kilbourn Park, Old Irving Park, The Villa)",
  "Jefferson Park (Gladstone Park, Jefferson Park)",
  "Kenwood (Kenwood)",
  "Lakeview (Lake View East, North Halsted, West Lakeview, Wrigleyville)",
  "Lincoln Park (DePaul, Old Town Triangle, Park West, Lincoln Park, Ranch Triangle, Sheffield Neighbors, Wrightwood Neighbors)",
  "Lincoln Square (Bowmanville, Budlong Woods, Lincoln Square, Ravenswood, Ravenswood Gardens)",
  "Logan Square (Logan Square, Bucktown, Palmer Square)",
  "Lower West Side (Heart of Chicago, Lower West Side, Pilsen)",
  "McKinley Park (McKinley Park)",
  "Montclare (Montclare)",
  "Morgan Park (Beverly Woods, Kennedy Park, Morgan Park, West Morgan Park)",
  "Mount Greenwood (Mount Greenwood, Talley’s Corner)",
  "Near North Side (Cabrini-Green, Dearborn Parkway, The Gold Coast, Goose Island, Magnificent Mile, Near North Side, Old Town, River North, River West, State Parkway, Streeterville)",
  "Near South Side (Dearborn Park, Near South Side, Museum Park, Central Station, Prairie Avenue Historic District)",
  "Near West Side (Columbus Circle, Greektown, Little Italy, Medical Center, Near West Side, Tri-Taylor, Fulton River District, University Village)",
  "New City (Back of the Yards, Canaryville, New City)",
  "North Center (Northcenter, Roscoe Village, Saint Ben’s)",
  "North Lawndale (North Lawndale)",
  "North Park (Hollywood Park, North Park, Pulaski Park)",
  "Norwood Park (Big Oaks, Norwood Park, Old Norwood, Oriole Park, Union Ridge)",
  "O’Hare (O’Hare, Schorsch Forest View)",
  "Oakland (Oakland)",
  "Portage Park (Portage Park, Six Corners)",
  "Pullman (Cottage Grove Heights, Pullman)",
  "Riverdale (Altgeld Gardens, Eden Green, Golden Gate, Riverdale)",
  "Rogers Park (Loyola, Rogers Park)",
  "Roseland (Fernwood, Princeton Park, Roseland)",
  "South Chicago (South Chicago)",
  "South Deering (Jeffrey Manor, South Deering)",
  "South Lawndale (Little Village, South Lawndale, Marshall Square)",
  "South Shore (Jackson Park Highlands, South Shore)",
  "Uptown (Clarendon Park, Buena Park, New Chinatown, Sheridan Park, Uptown)",
  "Washington Heights (Brainerd, Longwood Manor, Washington Heights)",
  "Washington Park (Washington Park)",
  "West Elsdon (West Elsdon)",
  "West Englewood (West Englewood)",
  "West Garfield Park (West Garfield Park)",
  "West Lawn (Ford City, West Lawn)",
  "West Pullman (West Pullman)",
  "West Ridge (Nortown, Peterson Park, Rosehill, West Ridge, West Rogers Park)",
  "West Town (East Village, Noble Square, Ukrainian Village, Smith Park, West Town, Wicker Park)",
  "Woodlawn (Woodlawn)",
];
